### ISSUE TITLE
How to download the deeplabv3 model in your code

### ISSUE THREAD

**Issue by zhongwenkun886** [FionaZZ92/OpenVINO#1]
Hi ,FionaZZ92,
Could you please tell me how to download the DeeplabV3+_MobileNetV2 model (DeeplabV3plus_mobileNetV2.pb) in your OpenVINO/DeeplabV3+_MobileNetV2/script.sh ?
Thanks!

**Comment by PINTO0309** [comment]
https://github.com/tensorflow/models/blob/master/research/deeplab/local_test_mobilenetv2.sh

**Comment by zhongwenkun886** [comment]
thanks
